<?php
if( function_exists('register_field_group') ):

register_field_group(array (
    'key' => 'group_54f4386332a0c',
    'title' => 'Campi Categorie',
    'fields' => array (
        array (
            'key' => 'field_54f441523dde0',
            'label' => 'Ordine',
            'name' => 'order',
            'prefix' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_55000d12e315d',
            'label' => 'Immagine sfondo',
            'name' => 'bg',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'caring-line',
            ),
        ),
        array (
            array (
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'coloring-line',
            ),
        ),
        array (
            array (
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'straightening-line',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54ef2e6ec1f2d-4',
    'title' => 'Canvas Homepage',
    'fields' => array (
        array (
            'key' => 'field_54ef2ee8cbed0',
            'label' => 'Titolo',
            'name' => 'titolo-canvas',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ef2ef9cbed1',
            'label' => 'Sottotitolo',
            'name' => 'sottotitolo-canvas',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ef2f11cbed2',
            'label' => 'Pulsante',
            'name' => 'pulsante-canvas',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/heritage.php',
            ),
        ),
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/caring.php',
            ),
        ),
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/coloring.php',
            ),
        ),
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/straightening.php',
            ),
        ),
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/inspiration.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54ecad0a5bbb4',
    'title' => 'Heritage',
    'fields' => array (
        array (
            'key' => 'field_54ecad14a37b3',
            'label' => 'Titolo',
            'name' => 'titolo_heritage',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecad1ea37b4',
            'label' => 'Paragrafo',
            'name' => 'paragrafo_heritage',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 10,
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecad46a37b5',
            'label' => 'Immagine di sfondo left',
            'name' => 'bg_img_heritage_sx',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'full',
            'library' => 'all',
        ),
        array (
            'key' => 'field_553fc01e3a062',
            'label' => 'Immagine di sfondo right',
            'name' => 'bg_img_heritage_dx',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'full',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'heritage',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54ec93e611d26',
    'title' => 'Inspiration',
    'fields' => array (
        array (
            'key' => 'field_54eca9fe9e495',
            'label' => 'Titolo',
            'name' => 'titolo_inspiration',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecaa5129aa0',
            'label' => 'Immagine paragrafo',
            'name' => 'immagine_paragrafo_inspiration',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        array (
            'key' => 'field_54eca90c2b756',
            'label' => 'Paragrafo',
            'name' => 'paragrafo_inspiration',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54eca9632b757',
            'label' => 'Immagine di sfondo',
            'name' => 'bg_img_inspiration',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'full',
            'library' => 'all',
        ),
        array (
            'key' => 'field_55015413bdf8e',
            'label' => 'Seleziona un prodotto Caring-line',
            'name' => 'seleziona_prodotto_caring',
            'prefix' => '',
            'type' => 'post_object',
            'instructions' => 'Puoi selezionare solo un prodotto delle tre sezioni',
            'required' => 0,
            'conditional_logic' => 0,
            'post_type' => array (
                0 => 'caring',
            ),
            'taxonomy' => '',
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array (
            'key' => 'field_5501a87b55bf0',
            'label' => 'Seleziona un prodotto Coloring line',
            'name' => 'seleziona_prodotto_coloring',
            'prefix' => '',
            'type' => 'post_object',
            'instructions' => 'Puoi selezionare solo un prodotto delle tre sezioni',
            'required' => 0,
            'conditional_logic' => 0,
            'post_type' => array (
                0 => 'coloring',
            ),
            'taxonomy' => '',
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array (
            'key' => 'field_5501a8aa55bf1',
            'label' => 'Seleziona un prodotto Straightening line',
            'name' => 'seleziona_prodotto_straightening',
            'prefix' => '',
            'type' => 'post_object',
            'instructions' => 'Puoi selezionare solo un prodotto delle tre sezioni',
            'required' => 0,
            'conditional_logic' => 0,
            'post_type' => array (
                0 => 'straightening',
            ),
            'taxonomy' => '',
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'inspiration',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54ecaf107f53d',
    'title' => 'Prodotto',
    'fields' => array (
        array (
            'key' => 'field_54ecaf26e77e0',
            'label' => 'Titolo',
            'name' => 'titolo_prodotto',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecaf4ee77e1',
            'label' => 'Sottotitolo',
            'name' => 'sottotitolo_prodotto',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecaf6de77e2',
            'label' => 'Dettaglio',
            'name' => 'dettaglio_prodotto',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecafa6e77e3',
            'label' => 'Immagine prodotto',
            'name' => 'immagine_prodotto',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        array (
            'key' => 'field_54ecafe8e77e4',
            'label' => 'Titolo paragrafo 1',
            'name' => 'titolo_paragrafo_1_prodotto',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecb000e77e5',
            'label' => 'Paragrafo 1',
            'name' => 'paragrafo_1_prodotto',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecb01ae77e6',
            'label' => 'Titolo paragrafo 2',
            'name' => 'titolo_paragrafo_2_prodotto',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecb03ae77e7',
            'label' => 'Paragrafo 2',
            'name' => 'paragrafo_2_prodotto',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f87345cb292',
            'label' => 'Titolo size',
            'name' => 'titolo_size_prodotto',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54ecb049e77e8',
            'label' => 'Testo size',
            'name' => 'testo_size_prodotto',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'caring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'coloring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'straightening',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

if( function_exists('register_field_group') ):

register_field_group(array (
    'key' => 'group_54f42d05e9381',
    'title' => 'Benefit 1',
    'fields' => array (
        array (
            'key' => 'field_54f42d4c57976',
            'label' => 'Titolo benefit',
            'name' => 'titolo_benefit_1',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f42d6557977',
            'label' => 'sottotitolo benefit',
            'name' => 'sottotitolo_benefit_1',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f42d7357978',
            'label' => 'Immagine sfondo benefit',
            'name' => 'immagine_benefit_1',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'large',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'caring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'coloring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'straightening',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54f4720056baf',
    'title' => 'Benefit 2',
    'fields' => array (
        array (
            'key' => 'field_54f47200599ef',
            'label' => 'Titolo benefit',
            'name' => 'titolo_benefit_2',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f4720059a0b',
            'label' => 'sottotitolo benefit',
            'name' => 'sottotitolo_benefit_2',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f4720059a25',
            'label' => 'Immagine sfondo benefit',
            'name' => 'immagine_benefit_2',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'large',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'caring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'coloring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'straightening',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_55084448e1025',
    'title' => 'Benefit 3',
    'fields' => array (
        array (
            'key' => 'field_550844619f6f6',
            'label' => 'Titolo benefit',
            'name' => 'titolo_benefit_3',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_550844769f6f7',
            'label' => 'Sottotitolo benefit',
            'name' => 'sottotitolo_benefit_3',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_550844989f6f8',
            'label' => 'Immagine sfondo benefit',
            'name' => 'immagine_benefit_3',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'large',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'caring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'coloring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'straightening',
            ),
        ),
    ),
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_54f4723ea3e5d',
    'title' => 'Kit composition',
    'fields' => array (
        array (
            'key' => 'field_54f4723ea695c',
            'label' => 'Titolo',
            'name' => 'titolo_kit',
            'prefix' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_54f4723ea697e',
            'label' => 'Immagine kit',
            'name' => 'immagine_kit',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'large',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'caring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'coloring',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'straightening',
            ),
        ),
    ),
    'menu_order' => 4,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

endif;

endif;
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_57a1be93b0343',
    'title' => 'HP-carousel',
    'fields' => array (
        array (
            'key' => 'field_57a1be9e84813',
            'label' => 'slider-item',
            'name' => 'slider-item',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => array (
                array (
                    'key' => 'field_57a1bfcd5a2fb',
                    'label' => 'titolo slider',
                    'name' => 'titolo-slider',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_57a1bfd95a2fc',
                    'label' => 'sottotitolo slider',
                    'name' => 'sottotitolo_slider',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_57a1bfec5a2fd',
                    'label' => 'label bottone',
                    'name' => 'label_bottone',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_57a1bffd5a2fe',
                    'label' => 'link slider',
                    'name' => 'link_slider',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_57a1c0575a300',
                    'label' => 'immagine sfondo',
                    'name' => 'immagine_sfondo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_57a1c0085a2ff',
                    'label' => 'isvideo',
                    'name' => 'isvideo',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'isVideo' => 'true',
                    ),
                    'default_value' => array (
                    ),
                    'layout' => 'vertical',
                    'toggle' => 0,
                ),
                array (
                    'key' => 'field_57a31369f82dd',
                    'label' => 'id video youtube',
                    'name' => 'id_video_youtube',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'front-page.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;